morpheus_url: ""
morpheus_api: "{{ morpheus_url }}/api"
morpheus_token: ""
verify_ssl: true

# morpheus_instancetypes:
#   - name: Test Builds
#     code: testbuilds
#     category: OS
#     featured: "true"
