---
dependencies: []

galaxy_info:
  role_name: groups
  author: Nick Celebic
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
  description: Role for creating groups in Morpheus
