morpheus_url: ""
morpheus_api: "{{ morpheus_url }}/api"
morpheus_token: ""
verify_ssl: true

# morpheus_settings:
#   showPricing: "false"
#   hideDatastoreStats: "false"
#   cloudInitUsername: "root"
#   cloudInitPassword: "{{ lookup(something) }}"
